disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - nesting
  - function_parameter_count
  - line_length
  - blanket_disable_command
opt_in_rules: # some rules are only opt-in
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
  - file_name
  - empty_string
  - convenience_type
  - toggle_bool
  - first_where
  - modifier_order
  - prohibited_interface_builder

analyzer_rules:
  - unused_declaration
  - unused_import

included: # paths to include during linting. `--path` is ignored if present.
  - ./KBMobileBankingInterviewTest
  - ./KBMobileBankingInterviewTestTests
  - ./KBMobileBankingInterviewTestUITests

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly. Give warning only for force casting

force_try:
  severity: warning # explicitly. Give warning only for force try

function_body_length: 
  - 200 # warning
  - 400 # error

# or they can set both explicitly
file_length:
  warning: 500
  error: 800

large_tuple: # warn user when using 3 values in tuple, give error if there are 4
   - 3
   - 4
   
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 35
    error: 40
  excluded: iPhone # excluded via string
reporter: "xcode"

